# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        interval = 5
}

#order += "disk /"
order += "ipv6"
#order += "run_watch DHCP"
#order += "path_exists VPN"
order += "wireless wlan0"
order += "ethernet erpk"
order += "ethernet tc"
order += "ethernet core"
order += "ethernet mgmt"
order += "battery 0"
order += "load"
order += "cpu_usage"
order += "memory"
order += "tztime local"
order += "volume master"

wireless wlan0 {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}

ethernet erpk {
        format_up = "erpk: %ip"
        format_down = "erpk: down"
}

ethernet core {
        format_up = "core: %ip"
        format_down = "core: down"
}

ethernet mgmt {
        format_up = "mgmt: %ip"
        format_down = "mgmt: down"
}

ethernet tc {
        format_up = "tc: %ip"
        format_down = "tc: down"
}

ethernet zniper {
        format_up = "zniper: %ip"
        format_down = "zniper: down"
}

battery 0 {
        format = "%status %percentage %remaining"
        hide_seconds = true
	integer_battery_capacity = true
}

run_watch DHCP {
        pidfile = "/var/run/dhclient*.pid"
}

run_watch VPN {
        pidfile = "/var/run/vpnc/pid"
}

path_exists VPN {
        # path exists when a VPN tunnel launched by nmcli/nm-applet is active
        path = "/proc/sys/net/ipv4/conf/core"
}

tztime local {
        format = "%d-%m-%Y %H:%M"
}

load {
        format = "%1min"
}

disk "/" {
        format = "%free"
}

memory {
        format = "RAM: %percentage_used"
        threshold_degraded = "10%"
        format_degraded = "RAM: %free"
}

#cpu_temperature 0 {
#        format = "T: %degrees °C"
#        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input"
#}

volume master {
        format = "♪: %volume"
        device = "pulse"
        mixer_idx = 0
}
