# /etc/zshrc - System-wide zsh interactive shell config (NimbleX)
# Loaded for all users on every interactive zsh session.

# ---- Home / End keybindings ----
bindkey '^[[H'   beginning-of-line   # Home (xterm/most terminals)
bindkey '^[[F'   end-of-line         # End
bindkey '^[[1~'  beginning-of-line   # Home (linux console / some terms)
bindkey '^[[4~'  end-of-line         # End
bindkey '^[[7~'  beginning-of-line   # Home (rxvt)
bindkey '^[[8~'  end-of-line         # End
bindkey '^[OH'   beginning-of-line   # Home (application mode)
bindkey '^[OF'   end-of-line         # End

# ---- Delete / Insert keybindings ----
bindkey '^[[3~'  delete-char         # Delete (xterm/kitty/most terminals)
bindkey '^[[P'   delete-char         # Delete (some terminals)
bindkey '^[[2~'  overwrite-mode      # Insert

# ---- Colors ----
# Load LS_COLORS from /etc/DIR_COLORS (or built-in defaults as fallback)
if [[ -f /etc/DIR_COLORS ]]; then
    eval "$(dircolors -b /etc/DIR_COLORS)"
else
    eval "$(dircolors -b)"
fi

alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lah --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
