#!/bin/bash

if [ "$1" = "--help" -o "$1" = "" ]; then
   echo "$0 - make NimbleX squashfs package"
   echo "usage: $0 source_directory [destination_file] [(optional)-keep-as-directory] [(optional)other_mksquashfs_arguments]"
   echo "note: destination file will be erased"
   exit
fi

if [ "$2" = "" ]; then
	DEST=`basename $1`.lzm
else
	DEST=$2
fi

ARCH="`uname -m`"
if [ "$ARCH" = "x86_64" -o "$ARCH"="i686" ]; then
	OPTS="-Xbcj x86"
fi

mksquashfs "$1" "$DEST" -comp xz -b 256k $OPTS -noappend $3 $4 $5 $6 $7 $8 $9
