#!/bin/bash
# convert .lzm compressed package into directory tree
#

if [ ! -f "$1" ]; then
   echo 
   echo "Convert .lzm compressed package into directory tree"
   echo "usage: $0 source_file.lzm existing_output_directory"
   exit 1
fi

if [ "$2" = "" ]; then
   DNAME=`basename $1 | cut -d "." -f 1`
else
   DNAME="$2"
fi

unsquashfs -f -dest "$DNAME" "$1" >/dev/null
