#!/bin/sh

# Convert rpm2lzm for use with NimbleX and the other Linux Live distros
# Author: Bogdan Radulescu [ nibmlex.net ]

if [ "$1" = "" ]; then
   echo
   echo "Convert the RPM package into .lzm package"
   echo "usage: $0 source_package.lzm"
   exit 1
fi

PKGNAME=$(basename $1 | sed "s/\\.rpm$//")
DIRNAME=$(dirname $1)

mkdir /tmp/$PKGNAME
rpm -ivh --nodeps --nomd5 --noorder --nosuggest --nodigest --force --nosignature --root=/tmp/$PKGNAME $1
rm -rf /tmp/$PKGNAME/var/lib/rpm
dir2lzm /tmp/$PKGNAME $DIRNAME/$PKGNAME.lzm
rm -rf /tmp/$PKGNAME