#!/bin/bash
# convert Slackware's TGZ package into .lzm compressed file
# which can be used as a LiveCD module
#
#

if [ "$1" = "" ]; then
   echo
   echo "Convert Slackware's TXZ package into .lzm compressed module"
   echo "usage: $0 source_filename.txz output_file.lzm"
   exit 1
fi

TMPDIR=/tmp/tgz2lzm$$

installpkg -root $TMPDIR $1
if [ $? != 0 ]; then echo "error installing package"; exit; fi

if [ "$2" = "" ]; then
   LZM=`basename $1 | cut -d "." -f 1`.lzm
else
   LZM=$2
fi

mksquashfs $TMPDIR "$2" -b 256K
if [ $? != 0 ]; then echo "error building compressed image"; exit; fi

rm -Rf $TMPDIR
